/**
 * Regenerates `client/src/domain/library.ts` from free-exercise-db.
 *
 *   curl -sL https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json -o /tmp/fedb.json
 *   node scripts/import-library.mjs /tmp/fedb.json
 *
 * ── Why this source ─────────────────────────────────────────────────────────
 *
 * It replaced an openGym import on 2026-09-06, one commit after that import
 * landed. openGym's data was AGPL by way of openGym and, underneath that,
 * unattributed and shaped like the commercially-distributed ExerciseDB — so the
 * chain of title could not be established. free-exercise-db is released into the
 * **public domain under the Unlicense**, which removes both the copyleft
 * obligation and the uncertainty. See NOTICE.md.
 *
 * It is also the better dataset for this app despite being smaller: 188
 * bodyweight entries against 325, but each carries `force` (push / pull /
 * static), `category` and `level`, which are the axes the five ladders are
 * actually built on. openGym's records carried a body-part string and nothing
 * that mapped onto how this programme is organised.
 *
 * ── Two filters, both deliberate ────────────────────────────────────────────
 *
 *   - **Bodyweight only.** Zero equipment is a hard constraint and was not among
 *     the decisions reversed on 2026-09-04. `equipment: null` counts — a handful
 *     of stretches record no equipment rather than "body only".
 *   - **No image fields.** free-exercise-db DOES ship its images, unlike openGym,
 *     so this is a choice rather than a repair: the user asked for no images in
 *     the tree, and this app's own figures are the hand-authored SVG rigs in
 *     `client/src/ui/figures/`. No binary is copied by this script.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const input = process.argv[2]
if (!input) {
  console.error('usage: node scripts/import-library.mjs /path/to/exercises.json')
  process.exit(2)
}

const raw = JSON.parse(readFileSync(input, 'utf8'))

const bodyweight = raw
  .filter((e) => e.equipment === 'body only' || e.equipment === null)
  .filter((e) => Array.isArray(e.instructions) && e.instructions.length > 0)
  .map((e) => ({
    id: e.id,
    name: e.name,
    category: e.category,
    force: e.force ?? null,
    level: e.level,
    mechanic: e.mechanic ?? null,
    primaryMuscles: e.primaryMuscles ?? [],
    secondaryMuscles: e.secondaryMuscles ?? [],
    instructions: e.instructions ?? [],
  }))
  .sort((a, b) => a.name.localeCompare(b.name, 'en'))

const dropped = raw.length - bodyweight.length
const header = `/**
 * A bodyweight exercise reference, derived from free-exercise-db.
 *
 * ── This is a REFERENCE, not a programme ────────────────────────────────────
 *
 * Nothing here is prescribed, scheduled, or reachable from the training path.
 * The programme is the five ladders in \`ladders.ts\` and the schedule in
 * \`schedule.ts\`, and this file must never become an input to either — the
 * governing invariant is that the prescription is a pure function of
 * \`sessionsDone\` (\`corpus/CLAUDE.md\`). It answers "what else does this kind of
 * training look like", which is a question the app previously had no answer to.
 *
 * It also does not reopen browsing on the training path. The app still arrives
 * with the answer already made; this is a page you go to, not a menu you are
 * handed on the way to a set.
 *
 * ── Provenance ─────────────────────────────────────────────────────────────
 *
 * Generated by \`scripts/import-library.mjs\` from
 * **free-exercise-db** (https://github.com/yuhonas/free-exercise-db), released
 * into the **public domain under the Unlicense**. There is no attribution
 * requirement and no copyleft obligation; NOTICE.md credits it anyway, because
 * "we did not have to" is a poor reason not to.
 *
 * This replaced an openGym import that stood for exactly one commit. That data
 * was AGPL by way of openGym and unattributed underneath it — see NOTICE.md for
 * why that mattered and why this source is the better answer.
 *
 * ${bodyweight.length} of free-exercise-db's ${raw.length} entries survive: bodyweight, and carrying
 * instructions. ${dropped} were dropped — almost all of them needing equipment this app
 * does not allow, plus two that ship with no instructions at all. Image fields
 * are dropped by choice; the upstream ships them, and no binary was copied.
 *
 * DO NOT EDIT BY HAND — re-run the generator.
 */

/** What the movement asks of you. \`null\` where upstream records none. */
export type LibraryForce = 'push' | 'pull' | 'static'

/** One reference exercise. Content only; nothing here drives a prescription. */
export interface LibraryExercise {
  /** free-exercise-db's own slug id, so a re-import can be diffed against this. */
  readonly id: string
  readonly name: string
  readonly category: string
  /** Maps onto how this programme is organised, which is why it is kept. */
  readonly force: LibraryForce | null
  readonly level: string
  readonly mechanic: string | null
  readonly primaryMuscles: readonly string[]
  readonly secondaryMuscles: readonly string[]
  readonly instructions: readonly string[]
}

export const LIBRARY: readonly LibraryExercise[] = `

writeFileSync('client/src/domain/library.ts', `${header}${JSON.stringify(bodyweight, null, 2)} as const\n`)
console.log(`kept ${bodyweight.length} bodyweight of ${raw.length}; dropped ${dropped}`)
