/**
 * Regenerates `client/src/domain/library.ts` from an openGym checkout.
 *
 *   node scripts/import-library.mjs /path/to/openGym
 *
 * The generator exists so the import is reproducible and its filters are
 * readable, rather than the data arriving as an 800KB paste nobody can audit.
 * See NOTICE.md for the licence position and the unresolved upstream provenance;
 * read it before re-running this.
 *
 * Two filters, both deliberate:
 *
 *   - **Bodyweight only.** Zero equipment is a hard constraint here and was not
 *     among the decisions reversed on 2026-09-04.
 *   - **No image or animation fields.** openGym's records name `.jpg`/`.gif`
 *     assets that its repository does not contain, so the fields would resolve
 *     to nothing. No binary asset is copied by this script, by design.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2]
if (!root) {
  console.error('usage: node scripts/import-library.mjs /path/to/openGym')
  process.exit(2)
}

const source = readFileSync(join(root, 'frontend/src/lib/exercises-data.js'), 'utf8')
const raw = JSON.parse(source.replace(/^export const EXDB=/, '').replace(/;?\s*$/, ''))

const bodyweight = raw
  .filter((e) => e.eq === 'body weight')
  .map((e) => ({
    id: e.id,
    name: e.n,
    bodyPart: e.bp,
    target: e.tg,
    majorMuscle: e.mg ?? null,
    secondaryMuscles: e.sm ?? [],
    steps: e.st ?? [],
  }))
  .sort((a, b) => a.name.localeCompare(b.name, 'en'))

const dropped = raw.length - bodyweight.length
const header = `/**
 * A bodyweight exercise reference, derived from openGym.
 *
 * ── This is a REFERENCE, not a programme ────────────────────────────────────
 *
 * Nothing here is prescribed, scheduled, or reachable from the training path.
 * The programme is the five ladders in \`ladders.ts\` and the schedule in
 * \`schedule.ts\`, and this file must never become an input to either — the
 * governing invariant is that the prescription is a pure function of
 * \`sessionsDone\` (\`corpus/CLAUDE.md\`). It answers "what else does this kind of
 * training look like", which is a question the app previously had no answer to
 * at all.
 *
 * It also does not reopen browsing on the training path. The app still arrives
 * with the answer already made; this is a page you go to, not a menu you are
 * handed on the way to a set.
 *
 * ── Provenance ─────────────────────────────────────────────────────────────
 *
 * Generated by \`scripts/import-library.mjs\` from openGym
 * (AGPL v3.0, Copyright (C) 2026 Duarte Santos). **Importing it is why this
 * repository is AGPL-licensed.** openGym does not attribute the data upstream and
 * it is shaped like the commercially-distributed ExerciseDB, so the chain of
 * title is unresolved — see NOTICE.md, which records that rather than papering
 * over it.
 *
 * ${bodyweight.length} of openGym's ${raw.length} entries survive the bodyweight filter; ${dropped} need
 * equipment this app does not allow. Image and animation fields are dropped:
 * openGym names assets its repository does not ship, and no binary was copied.
 *
 * DO NOT EDIT BY HAND — re-run the generator.
 */

/** One reference exercise. Content only; nothing here drives a prescription. */
export interface LibraryExercise {
  /** openGym's own id, kept so a re-import can be diffed against this file. */
  readonly id: string
  readonly name: string
  readonly bodyPart: string
  readonly target: string
  readonly majorMuscle: string | null
  readonly secondaryMuscles: readonly string[]
  readonly steps: readonly string[]
}

export const LIBRARY: readonly LibraryExercise[] = `

const body = JSON.stringify(bodyweight, null, 2)
writeFileSync('client/src/domain/library.ts', `${header}${body} as const\n`)
console.log(`kept ${bodyweight.length} bodyweight of ${raw.length}; dropped ${dropped}`)
